import { existsSync, readFileSync, mkdirSync, appendFileSync } from "node:fs"; import { dirname } from "node:path"; import { spawnSync } from "node:child_process"; import { PiRequest, PiResult, UsageBreakdown, usageZero, addTurn } from "./data_types"; import { operatorEnv, nowIso } from "./utils";
const PI_PATH=process.env.PI_PATH||"pi", MODELS=process.env.PI_MODELS_PATH||`${process.env.HOME}/.pi/agent/models.json`;
function count(v:string){const s=v.slice(-1).toUpperCase();return s==="K"?+v.slice(0,-1)*1e3:s==="M"?+v.slice(0,-1)*1e6:+v;}
let catalogCache:Array<[string,string,number]>|null=null; export function catalog(){if(catalogCache)return catalogCache;const r=spawnSync(PI_PATH,["--list-models"],{encoding:"utf8",timeout:30000,env:operatorEnv()});if(r.status!==0)return catalogCache=[];return catalogCache=(r.stdout||"").split("\n").slice(1).flatMap((l:string)=>{const c=l.trim().split(/\s+/);if(c.length<3)return [];try{return [[c[0],c[1],count(c[2])] as [string,string,number]]}catch{return []}});}
export function resolveModel(pattern:string){const all=catalog();if(pattern.includes("/")){const [p,...rest]=pattern.split("/");const id=rest.join("/");if(all.some(x=>x[0]===p&&x[1]===id))return [p,id] as const;}const m=all.filter(x=>pattern===x[1]||x[1].includes(pattern));const exact=m.filter(x=>x[1]===pattern||x[1].endsWith("/"+pattern));const out=exact.length===1?exact:exact.length?exact:m;if(out.length!==1)throw new Error(out.length?`model pattern ${pattern} is ambiguous: ${JSON.stringify(out)}`:`model pattern ${pattern} not found in pi --list-models`);return [out[0][0],out[0][1]] as const;}
export function contextWindow(provider:string,id:string){try{const j=JSON.parse(readFileSync(MODELS,"utf8"));const x=j.providers?.[provider]?.models?.find((m:any)=>m.id===id);if(x)return x.contextWindow||0;}catch{}return catalog().find(x=>x[0]===provider&&x[1]===id)?.[2]||0;}
const textOf=(x:any)=>Array.isArray(x?.content)?x.content.filter((p:any)=>p?.type==="text").map((p:any)=>p.text||"").join(""):""; const clip=(x:string,n:number)=>x.length<=n?x:x.slice(0,n).trimEnd()+"…";
function contextTokens(u:any){return u?.totalTokens||((u?.input||0)+(u?.output||0)+(u?.cacheRead||0)+(u?.cacheWrite||0));}
export async function run(req:PiRequest,onEvent?:(e:any)=>void,onSpawn?:(pid:number)=>void,onExit?:(pid:number)=>void):Promise<PiResult>{const [provider,id]=resolveModel(req.model);const args=["-p","--mode","json","--provider",provider,"--model",id,"--thinking",req.thinking,"--session-id",req.sessionId,"--session-dir",req.sessionDir,"--system-prompt",req.systemPrompt];if(req.tools?.length)args.push("--tools",req.tools.join(","));for(const e of req.extensions)args.push("-e",e);args.push(req.prompt);mkdirSync(dirname(req.rawOutputPath),{recursive:true});const proc=Bun.spawn([PI_PATH,...args],{cwd:req.cwd,env:operatorEnv(),stdin:"ignore",stdout:"pipe",stderr:"pipe"});const pid=proc.pid;onSpawn?.(pid);const result:PiResult={text:"",returncode:0,session_id:req.sessionId,tokens:0,cost:0,usage:usageZero(),context_tokens:0,context_window:contextWindow(provider,id)};let buffer="";const reader=proc.stdout.getReader();const decoder=new TextDecoder();while(true){const x=await reader.read();if(x.done)break;buffer+=decoder.decode(x.value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const raw of lines){appendFileSync(req.rawOutputPath,raw+"\n");let e:any;try{e=JSON.parse(raw)}catch{continue}if(e.type==="message_end"&&e.message?.role==="assistant"){const t=textOf(e.message);if(t)result.text=t;const u=e.message.usage||{},turn=contextTokens(u);result.tokens+=turn;addTurn(result.usage,u,turn);result.cost+=(u.cost?.total||0);if(turn&&!(["aborted","error"] as string[]).includes(e.message.stopReason))result.context_tokens=turn;}onEvent?.(e);}}if(buffer.trim())appendFileSync(req.rawOutputPath,buffer+"\n");result.returncode=await proc.exited;onExit?.(pid);if(result.returncode!==0&&!result.text){const err=await new Response(proc.stderr).text();throw new Error(`pi exited ${result.returncode}: ${err.trim().slice(-800)}`);}return result;}
export class ToolCallTracker {open=new Map<string,{tool:string,args:any,started:string,clock:number}>();observe(e:any){if(e.type==="message_end"){for(const b of e.message?.content||[])if(b?.type==="toolCall")this.announce(b.id,b.name,b.arguments);return;}if(e.type==="tool_execution_start"){this.announce(e.toolCallId,e.toolName,e.args);return;}if(e.type!=="tool_execution_end")return;const o=this.open.get(String(e.toolCallId))||{} as any;this.open.delete(String(e.toolCallId));const args=e.args||o.args||{};const value=Object.values(args).find((x:any)=>typeof x==="string"&&x.trim())||"";return {tool:e.toolName||o.tool||"tool",tool_call_id:String(e.toolCallId||""),args,label:`${e.toolName||o.tool||"tool"}: ${clip(String(value),80)}`,ok:!e.isError,result_snippet:clip(textOf(e.result||{}),20000),started_at:o.started||nowIso(),ended_at:nowIso(),duration_ms:o.clock?Date.now()-o.clock:0};}announce(id:any,tool:any,args:any){if(!id)return;const k=String(id),old=this.open.get(k);this.open.set(k,{tool:tool||old?.tool||"",args:args||old?.args||{},started:old?.started||nowIso(),clock:old?.clock||Date.now()});}}
